### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied 64x115 and 5x29

### ISSUE THREAD

**Issue by atif19663** [ValerianRey/fed_iot_guard#29]
mat1 and mat2 shapes cannot be multiplied 64x115 and 5x29
how to solve this

**Comment by ValerianRey** [comment]
Can you give more context? Did you make any change to the code? if so, which changes? Which arguments did you use when running the script?

**Comment by ValerianRey** [comment]
Closing the issue as there was no update for 2 months.

**Comment by Rasha1990** [comment]
Traceback (most recent call last):
  File "main_multihead.py", line 491, in <module>
    ret = main(args.seed)
  File "main_multihead.py", line 322, in main
    plt.plot(epochs, valid_loss[:len(epochs)], label='Validation loss')
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/pyplot.py", line
3019, in plot
    return gca().plot(
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_axes.py",
line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_base.py",
line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_base.py",
line 501, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (666,)
and (96,)
